name: release Windows desktop (Avalonia UI)

on:
  workflow_dispatch:
    inputs:
      release_tag:
        required: false
        type: string
  push:
    branches:
      - master
      - build

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - runtime: win-x64
            package_arch: "windows-64"
            self_contained: false
          - runtime: win-arm64
            package_arch: "windows-arm64"
            self_contained: false
          - runtime: win-x64
            package_arch: "windows-64-SelfContained"
            self_contained: true
          - runtime: win-arm64
            package_arch: "windows-arm64-SelfContained"
            self_contained: true

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2
      with:
        submodules: 'recursive'
        fetch-depth: '0'

    - name: Set output paths
      run: echo "output_path=${{ github.workspace }}/v2rayN/Release/${{ matrix.package_arch }}" >> $GITHUB_ENV

    - name: Setup
      uses: actions/setup-dotnet@v4.3.1
      with:
        dotnet-version: '8.0.x'

    - name: Build
      if: matrix.self_contained == false
      run: |
        cd v2rayN 
        dotnet publish ./v2rayN.Desktop/v2rayN.Desktop.csproj -c Release -r ${{ matrix.runtime }}   --self-contained=false -p:EnableWindowsTargeting=true -o "${{ env.output_path }}"
        dotnet publish ./AmazTool/AmazTool.csproj             -c Release -r ${{ matrix.runtime }}   --self-contained=false -p:EnableWindowsTargeting=true -o "${{ env.output_path }}"

    - name: Build self contained
      if: matrix.self_contained == true
      run: |
        cd v2rayN 
        dotnet publish ./v2rayN.Desktop/v2rayN.Desktop.csproj -c Release -r ${{ matrix.runtime }}   --self-contained=true -p:EnableWindowsTargeting=true -o "${{ env.output_path }}"
        dotnet publish ./AmazTool/AmazTool.csproj             -c Release -r ${{ matrix.runtime }}   --self-contained=true -p:EnableWindowsTargeting=true -p:PublishTrimmed=true -o "${{ env.output_path }}"

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4.6.2
      with:
        name: v2rayN-${{ matrix.package_arch }}-desktop
        path: "${{ env.output_path }}"
        compression-level: 6

    # release zip archive
    - name: Package release zip archive
      if: github.event.inputs.release_tag != ''
      run: |
        chmod 755 package-release-zip.sh
        ./package-release-zip.sh ${{ matrix.package_arch }} "${{ env.output_path }}"
        mv "v2rayN-${{ matrix.package_arch }}.zip" "v2rayN-${{ matrix.package_arch }}-desktop.zip"

    - name: Upload zip archive to release
      uses: svenstaro/upload-release-action@v2
      if: github.event.inputs.release_tag != ''
      with:
        file: ${{ github.workspace }}/v2rayN*.zip
        tag: ${{ github.event.inputs.release_tag }}
        file_glob: true
        prerelease: true

    # upload 7z archive to release for testing
    - name: Install 7z
      uses: milliewalky/setup-7-zip@v2

    - name: Package release 7z archive
      run: |
        chmod 755 package-release-7z.sh
        ./package-release-7z.sh ${{ matrix.package_arch }} "${{ env.output_path }}"
        mv "v2rayN-${{ matrix.package_arch }}.7z" "v2rayN-${{ matrix.package_arch }}-desktop.7z"

    - name: Create git tag
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          try {
            await github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/build-${{ github.sha }}',
              sha: context.sha
            });
            core.info('✅ Tag created: build-${{ github.sha }}');
          } catch (err) {
            if (err.status === 422) {
              core.info('⚠️ Tag already exists: build-${{ github.sha }} (no override)');
            } else {
              throw err;
            }
          }

    - name: Upload 7z archive to release for testing
      uses: svenstaro/upload-release-action@v2
      if: github.event_name == 'push'
      with:
        file: ${{ github.workspace }}/v2rayN*.7z
        release_name: build-${{ github.sha }}
        tag: build-${{ github.sha }}
        file_glob: true
        prerelease: true
